"""
Tests verifying that spending-pattern ``risk`` predictions include structured
``supporting_signals`` so BehavioralAccuracyTracker._infer_risk_accuracy() can
close the learning loop without relying on fragile description parsing.

Background
----------
``_check_spending_patterns()`` was the only prediction generator that did NOT
populate ``supporting_signals``.  The tracker's ``_infer_risk_accuracy()``
method (tracker.py lines 703-705) expects three fields:

* ``category``   — the spending category that was flagged
* ``amount``     — the dollar amount spent in that category
* ``percentage`` — the share of total spending (0-100 scale)

Without these fields the tracker immediately falls back to regex-parsing the
description, which is fragile for category names with special characters and
which also prevented the fast-path from firing, leaving all risk predictions
permanently unresolved.

This module verifies that every risk prediction generated by
``_check_spending_patterns()`` contains the required signals.
"""

import json
from datetime import datetime, timedelta, timezone
from unittest.mock import MagicMock, patch

import pytest

from models.user_model import Prediction


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_engine(db):
    """Construct a PredictionEngine with minimal mocked dependencies.

    Uses the same pattern as the other supporting-signals test modules so
    fixtures are compatible.
    """
    from services.prediction_engine.engine import PredictionEngine

    ums = MagicMock()
    ums.store_prediction.return_value = None
    ums.get_signal_profile.return_value = None

    engine = PredictionEngine(db=db, ums=ums)
    return engine


def _make_transaction_row(category: str, amount: float, days_ago: int = 5) -> MagicMock:
    """Return a fake DB row for a ``finance.transaction.new`` event.

    Args:
        category: The spending category (e.g. 'groceries', 'dining').
        amount:   The transaction amount in dollars (positive).
        days_ago: How many days ago the transaction occurred.

    Returns:
        A MagicMock that behaves like a sqlite3.Row when accessed by key.
    """
    ts = (datetime.now(timezone.utc) - timedelta(days=days_ago)).isoformat()
    payload = json.dumps({
        "category": category,
        "amount": -abs(amount),   # Expenses are negative in the source data
        "date": ts,
    })
    row = MagicMock()
    row.__getitem__ = MagicMock(side_effect=lambda k: {
        "payload": payload,
        "timestamp": ts,
    }[k])
    row.get = MagicMock(side_effect=lambda k, d=None: {
        "payload": payload,
        "timestamp": ts,
    }.get(k, d))
    return row


def _build_transactions(category_amounts: dict[str, float]) -> list[MagicMock]:
    """Build a list of transaction rows from a {category: amount} mapping.

    Each amount is split into a single transaction for simplicity.
    """
    rows = []
    for cat, amt in category_amounts.items():
        rows.append(_make_transaction_row(cat, amt))
    return rows


# ---------------------------------------------------------------------------
# Core signal presence tests
# ---------------------------------------------------------------------------

class TestRiskPredictionSignals:
    """_check_spending_patterns() must populate supporting_signals on every risk prediction."""

    @pytest.mark.asyncio
    async def test_risk_prediction_includes_category(self, db):
        """A dominant spending category produces a risk prediction with 'category' in signals.

        The tracker's _infer_risk_accuracy() extracts the category from signals
        (line 703) before attempting the regex fallback.  This test ensures the
        primary path is exercised.
        """
        engine = _make_engine(db)
        # groceries = $600, dining = $100 → groceries is 85.7% of total, exceeds 25% + $200
        transactions = _build_transactions({"groceries": 600.0, "dining": 100.0})
        # Add 5+ rows so the engine doesn't skip for insufficient data
        while len(transactions) < 5:
            transactions.append(_make_transaction_row("dining", 10.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds, "Expected at least one risk prediction for dominant spending category"

        pred = risk_preds[0]
        assert pred.supporting_signals is not None, "supporting_signals must not be None"
        assert "category" in pred.supporting_signals, (
            "risk prediction must include 'category' so "
            "_infer_risk_accuracy() can identify the flagged spend category"
        )
        assert pred.supporting_signals["category"] == "groceries"

    @pytest.mark.asyncio
    async def test_risk_prediction_includes_amount(self, db):
        """Risk prediction supporting_signals includes 'amount' (dollar value).

        The tracker uses 'amount' to confirm whether flagged spending was
        in the expected range, supporting behavioral inferences.
        """
        engine = _make_engine(db)
        transactions = _build_transactions({"entertainment": 500.0, "utilities": 50.0})
        while len(transactions) < 5:
            transactions.append(_make_transaction_row("utilities", 5.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds, "Expected a risk prediction for entertainment spending"

        signals = risk_preds[0].supporting_signals
        assert "amount" in signals, "risk prediction must include 'amount'"
        # Amount should be close to 500 (within float rounding)
        assert abs(signals["amount"] - 500.0) < 1.0, (
            f"Expected amount ~500, got {signals['amount']}"
        )

    @pytest.mark.asyncio
    async def test_risk_prediction_includes_percentage(self, db):
        """Risk prediction supporting_signals includes 'percentage' (0-100 scale).

        The tracker uses 'percentage' to verify the prediction was meaningful
        (i.e., the spend was genuinely anomalous as a share of budget).
        """
        engine = _make_engine(db)
        # groceries = $300 out of $400 total = 75%
        transactions = _build_transactions({"groceries": 300.0, "transport": 100.0})
        while len(transactions) < 5:
            transactions.append(_make_transaction_row("transport", 5.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds, "Expected a risk prediction"

        signals = risk_preds[0].supporting_signals
        assert "percentage" in signals, "risk prediction must include 'percentage'"
        # Expect ~75% (300/400) — allow ±2 for floating point
        assert 70 <= signals["percentage"] <= 80, (
            f"Expected percentage ~75, got {signals['percentage']}"
        )

    @pytest.mark.asyncio
    async def test_risk_prediction_includes_total_spending(self, db):
        """Risk prediction supporting_signals includes 'total_spending' for context.

        Knowing the total allows the tracker (and UI) to provide proportional
        context rather than absolute-only figures.
        """
        engine = _make_engine(db)
        transactions = _build_transactions({"dining": 400.0, "groceries": 100.0})
        while len(transactions) < 5:
            transactions.append(_make_transaction_row("groceries", 10.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds

        signals = risk_preds[0].supporting_signals
        assert "total_spending" in signals, "risk prediction must include 'total_spending'"
        assert signals["total_spending"] > 0

    @pytest.mark.asyncio
    async def test_risk_prediction_includes_transaction_count(self, db):
        """Risk prediction supporting_signals includes 'transaction_count'.

        The transaction count tells the tracker how much data backed the
        prediction — useful for evaluating prediction confidence calibration.
        """
        engine = _make_engine(db)
        # 8 transactions: 6 dining ($50 each = $300), 2 transport ($50 each = $100)
        transactions = [_make_transaction_row("dining", 50.0) for _ in range(6)]
        transactions += [_make_transaction_row("transport", 50.0) for _ in range(2)]

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds

        signals = risk_preds[0].supporting_signals
        assert "transaction_count" in signals, "risk prediction must include 'transaction_count'"
        assert signals["transaction_count"] == 8

    @pytest.mark.asyncio
    async def test_multiple_risk_predictions_all_have_signals(self, db):
        """When multiple categories trigger risk predictions, all include supporting_signals.

        Edge case: two categories each exceed the 25%/$200 threshold.  Both
        predictions must carry their own signals with the correct category value.
        """
        engine = _make_engine(db)
        # Both dining and entertainment dominate:
        # dining=$400 (50%), entertainment=$300 (37.5%), transport=$100 (12.5%)
        transactions = [
            _make_transaction_row("dining", 400.0),
            _make_transaction_row("entertainment", 300.0),
            _make_transaction_row("transport", 100.0),
        ]
        # Pad to ≥5 rows so the engine doesn't exit early
        transactions.append(_make_transaction_row("transport", 1.0))
        transactions.append(_make_transaction_row("transport", 1.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert len(risk_preds) >= 2, (
            "Expected at least 2 risk predictions when both dining and entertainment dominate"
        )

        categories_in_signals = {p.supporting_signals["category"] for p in risk_preds}
        assert "dining" in categories_in_signals, "dining risk prediction must include category"
        assert "entertainment" in categories_in_signals, (
            "entertainment risk prediction must include category"
        )

        # Every prediction must have supporting_signals
        for pred in risk_preds:
            assert pred.supporting_signals is not None
            assert "category" in pred.supporting_signals
            assert "amount" in pred.supporting_signals
            assert "percentage" in pred.supporting_signals


# ---------------------------------------------------------------------------
# Tracker integration: signals arrive in the format _infer_risk_accuracy() expects
# ---------------------------------------------------------------------------

class TestRiskSignalsTrackerCompatibility:
    """Verify signals match exactly what BehavioralAccuracyTracker._infer_risk_accuracy() reads."""

    @pytest.mark.asyncio
    async def test_signals_are_json_serializable(self, db):
        """Risk supporting_signals must survive json.dumps/json.loads round-trip.

        Signals are stored in the DB as JSON.  If any value is not
        serializable (e.g., a numpy float or datetime), storage silently breaks.
        """
        engine = _make_engine(db)
        transactions = _build_transactions({"groceries": 350.0, "utilities": 80.0})
        while len(transactions) < 5:
            transactions.append(_make_transaction_row("utilities", 5.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds

        for pred in risk_preds:
            # Should not raise
            serialized = json.dumps(pred.supporting_signals)
            recovered = json.loads(serialized)
            assert recovered["category"] == pred.supporting_signals["category"]
            assert abs(recovered["amount"] - pred.supporting_signals["amount"]) < 0.01

    @pytest.mark.asyncio
    async def test_category_field_matches_description(self, db):
        """The 'category' in supporting_signals must match the category in the description.

        Before this fix, the tracker parsed the description with regex to find
        the category (e.g. ``on 'groceries'``).  The signal must be consistent
        with the description so existing regex-fallback paths remain valid.
        """
        engine = _make_engine(db)
        transactions = _build_transactions({"groceries": 450.0, "transport": 80.0})
        while len(transactions) < 5:
            transactions.append(_make_transaction_row("transport", 5.0))

        with patch.object(engine.db, "get_connection") as mock_ctx:
            mock_conn = MagicMock()
            mock_conn.__enter__ = MagicMock(return_value=mock_conn)
            mock_conn.__exit__ = MagicMock(return_value=False)
            mock_conn.execute.return_value.fetchall.return_value = transactions
            mock_ctx.return_value = mock_conn

            predictions = await engine._check_spending_patterns({})

        risk_preds = [p for p in predictions if p.prediction_type == "risk"]
        assert risk_preds

        pred = risk_preds[0]
        category = pred.supporting_signals["category"]
        # The description format is: "Spending alert: $NNN on 'CATEGORY' this month ..."
        assert f"on '{category}'" in pred.description, (
            f"supporting_signals['category']={category!r} not found in description: "
            f"{pred.description!r}"
        )

    def test_prediction_model_stores_risk_signals(self):
        """Prediction model correctly stores dict supporting_signals for risk type."""
        pred = Prediction(
            prediction_type="risk",
            description="Spending alert: $450 on 'groceries' this month (75% of total)",
            confidence=0.5,
            confidence_gate="suggest",
            time_horizon="this_week",
            supporting_signals={
                "category": "groceries",
                "amount": 450.0,
                "percentage": 75.0,
                "total_spending": 600.0,
                "transaction_count": 8,
            },
        )
        assert pred.supporting_signals["category"] == "groceries"
        assert pred.supporting_signals["amount"] == 450.0
        assert pred.supporting_signals["percentage"] == 75.0
        assert pred.supporting_signals["total_spending"] == 600.0
        assert pred.supporting_signals["transaction_count"] == 8

    def test_risk_signals_json_round_trip(self):
        """Risk supporting_signals must survive DB storage round-trip."""
        signals = {
            "category": "dining",
            "amount": 320.50,
            "percentage": 64.1,
            "total_spending": 500.0,
            "transaction_count": 12,
        }
        stored = json.dumps(signals)
        recovered = json.loads(stored)
        assert recovered["category"] == "dining"
        assert abs(recovered["amount"] - 320.50) < 0.01
        assert abs(recovered["percentage"] - 64.1) < 0.01
        assert recovered["transaction_count"] == 12
