"""
Life OS — Task Manager

First-class task objects that can be created by the user, extracted by AI
from messages, or generated by rules. Every task carries its full context —
who it's related to, where it came from, what files are relevant.

When the user sits down to work on a task, the AI can surface everything
they need: the original email thread, the person's contact info, related
documents, and any deadlines.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from models.core import Priority, Task
from storage.database import DatabaseManager


class TaskManager:
    """Manages the lifecycle of tasks across all sources."""

    def __init__(self, db: DatabaseManager):
        self.db = db

    def create_task(
        self,
        title: str,
        description: Optional[str] = None,
        source: str = "user",
        source_event_id: Optional[str] = None,
        source_context: Optional[str] = None,
        domain: Optional[str] = None,
        priority: str = "normal",
        tags: Optional[list[str]] = None,
        due_date: Optional[str] = None,
        reminder_at: Optional[str] = None,
        estimated_minutes: Optional[int] = None,
        related_contacts: Optional[list[str]] = None,
        related_events: Optional[list[str]] = None,
    ) -> str:
        """Create a new task. Returns the task ID."""
        task_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        with self.db.get_connection("state") as conn:
            conn.execute(
                """INSERT INTO tasks 
                   (id, title, description, source, source_event_id, source_context,
                    domain, priority, tags, due_date, reminder_at, estimated_minutes,
                    related_contacts, related_events, status, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)""",
                (
                    task_id, title, description, source, source_event_id, source_context,
                    domain, priority,
                    json.dumps(tags or []),
                    due_date, reminder_at, estimated_minutes,
                    json.dumps(related_contacts or []),
                    json.dumps(related_events or []),
                    now, now,
                ),
            )
        return task_id

    def complete_task(self, task_id: str):
        """Mark a task as completed."""
        now = datetime.now(timezone.utc).isoformat()
        with self.db.get_connection("state") as conn:
            conn.execute(
                "UPDATE tasks SET status = 'completed', completed_at = ?, updated_at = ? WHERE id = ?",
                (now, now, task_id),
            )

    def update_task(self, task_id: str, **fields):
        """Update specific fields on a task."""
        allowed = {
            "title", "description", "domain", "priority", "tags",
            "due_date", "reminder_at", "estimated_minutes", "status",
        }
        updates = {k: v for k, v in fields.items() if k in allowed}
        if not updates:
            return

        # Serialize lists
        for key in ("tags", "related_contacts", "related_events"):
            if key in updates and isinstance(updates[key], list):
                updates[key] = json.dumps(updates[key])

        set_clause = ", ".join(f"{k} = ?" for k in updates)
        values = list(updates.values())
        values.append(datetime.now(timezone.utc).isoformat())
        values.append(task_id)

        with self.db.get_connection("state") as conn:
            conn.execute(
                f"UPDATE tasks SET {set_clause}, updated_at = ? WHERE id = ?",
                values,
            )

    def get_pending_tasks(
        self,
        domain: Optional[str] = None,
        priority: Optional[str] = None,
        limit: int = 50,
    ) -> list[dict]:
        """Get pending tasks, optionally filtered."""
        query = "SELECT * FROM tasks WHERE status = 'pending'"
        params: list[Any] = []

        if domain:
            query += " AND domain = ?"
            params.append(domain)
        if priority:
            query += " AND priority = ?"
            params.append(priority)

        query += """
            ORDER BY 
                CASE priority 
                    WHEN 'critical' THEN 1 WHEN 'high' THEN 2 
                    WHEN 'normal' THEN 3 ELSE 4 
                END,
                due_date ASC NULLS LAST
            LIMIT ?"""
        params.append(limit)

        with self.db.get_connection("state") as conn:
            rows = conn.execute(query, params).fetchall()
            return [self._row_to_dict(row) for row in rows]

    def get_overdue_tasks(self) -> list[dict]:
        """Get tasks past their due date."""
        now = datetime.now(timezone.utc).isoformat()
        with self.db.get_connection("state") as conn:
            rows = conn.execute(
                """SELECT * FROM tasks 
                   WHERE status = 'pending' AND due_date IS NOT NULL AND due_date < ?
                   ORDER BY due_date ASC""",
                (now,),
            ).fetchall()
            return [self._row_to_dict(row) for row in rows]

    def get_tasks_due_soon(self, hours: int = 24) -> list[dict]:
        """Get tasks due within the next N hours."""
        now = datetime.now(timezone.utc)
        deadline = (now + timedelta(hours=hours)).isoformat()
        with self.db.get_connection("state") as conn:
            rows = conn.execute(
                """SELECT * FROM tasks 
                   WHERE status = 'pending' AND due_date IS NOT NULL 
                   AND due_date BETWEEN ? AND ?
                   ORDER BY due_date ASC""",
                (now.isoformat(), deadline),
            ).fetchall()
            return [self._row_to_dict(row) for row in rows]

    def get_task_context(self, task_id: str) -> dict:
        """
        Get the full context for a task — the original event that spawned it,
        related contacts, and any connected files or events.
        """
        with self.db.get_connection("state") as conn:
            task_row = conn.execute("SELECT * FROM tasks WHERE id = ?", (task_id,)).fetchone()

        if not task_row:
            return {}

        task = self._row_to_dict(task_row)
        context = {"task": task}

        # Fetch source event if available
        if task.get("source_event_id"):
            with self.db.get_connection("events") as conn:
                event_row = conn.execute(
                    "SELECT * FROM events WHERE id = ?", (task["source_event_id"],)
                ).fetchone()
                if event_row:
                    context["source_event"] = dict(event_row)

        # Fetch related contacts
        contact_ids = task.get("related_contacts", [])
        if contact_ids:
            with self.db.get_connection("entities") as conn:
                placeholders = ",".join("?" * len(contact_ids))
                contacts = conn.execute(
                    f"SELECT * FROM contacts WHERE id IN ({placeholders})",
                    contact_ids,
                ).fetchall()
                context["related_contacts"] = [dict(c) for c in contacts]

        return context

    def ingest_ai_extracted_tasks(self, tasks: list[dict], source_event_id: str):
        """
        Store tasks extracted by the AI engine from messages/emails.
        Each task dict should have: title, due_hint (optional), priority.
        """
        for task_data in tasks:
            self.create_task(
                title=task_data.get("title", "Untitled task"),
                source="ai_extracted",
                source_event_id=source_event_id,
                priority=task_data.get("priority", "normal"),
                due_date=task_data.get("due_hint"),
            )

    def get_task_stats(self) -> dict:
        """Get summary statistics for the task dashboard."""
        with self.db.get_connection("state") as conn:
            pending = conn.execute(
                "SELECT COUNT(*) as cnt FROM tasks WHERE status = 'pending'"
            ).fetchone()["cnt"]

            completed_today = conn.execute(
                """SELECT COUNT(*) as cnt FROM tasks 
                   WHERE status = 'completed' 
                   AND completed_at > datetime('now', '-1 day')"""
            ).fetchone()["cnt"]

            overdue = conn.execute(
                """SELECT COUNT(*) as cnt FROM tasks 
                   WHERE status = 'pending' AND due_date IS NOT NULL 
                   AND due_date < datetime('now')"""
            ).fetchone()["cnt"]

            by_domain = conn.execute(
                """SELECT domain, COUNT(*) as cnt FROM tasks 
                   WHERE status = 'pending' GROUP BY domain"""
            ).fetchall()

        return {
            "pending": pending,
            "completed_today": completed_today,
            "overdue": overdue,
            "by_domain": {row["domain"] or "unassigned": row["cnt"] for row in by_domain},
        }

    @staticmethod
    def _row_to_dict(row) -> dict:
        d = dict(row)
        for field in ("tags", "related_contacts", "related_files", "related_events", "depends_on"):
            if field in d and isinstance(d[field], str):
                try:
                    d[field] = json.loads(d[field])
                except (json.JSONDecodeError, TypeError):
                    d[field] = []
        return d
