"""
Life OS — Task Manager

First-class task objects that can be created by the user, extracted by AI
from messages, or generated by rules. Every task carries its full context —
who it's related to, where it came from, what files are relevant.

When the user sits down to work on a task, the AI can surface everything
they need: the original email thread, the person's contact info, related
documents, and any deadlines.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Optional


from models.core import Priority, Task
from storage.database import DatabaseManager


class TaskManager:
    """Manages the lifecycle of tasks across all sources."""

    def __init__(self, db: DatabaseManager, event_bus: Any = None, ai_engine: Any = None):
        """
        Initialize the task manager.

        Args:
            db: Database manager for task persistence
            event_bus: Event bus for telemetry publishing
            ai_engine: AI engine for extracting action items from text
        """
        self.db = db  # Database access for tasks, events, and contacts tables
        self.bus = event_bus
        self.ai_engine = ai_engine

    async def _publish_telemetry(self, event_type: str, payload: dict):
        """Publish a telemetry event if the event bus is available."""
        if self.bus and self.bus.is_connected:
            await self.bus.publish(event_type, payload, source="task_manager")

    async def process_event(self, event: dict):
        """
        Process an event for potential task extraction.

        Analyzes actionable event types (emails, messages, calendar events)
        to extract AI-identified tasks using the local LLM. Task extraction
        is limited to events with substantial text content to avoid wasting
        LLM cycles on trivial messages like "ok" or "thanks".

        Actionable event types:
            - email.received: Incoming emails may contain requests
            - message.received: Direct messages may contain action items
            - calendar.event.created: Calendar descriptions may list TODOs

        Args:
            event: Event dict with type, payload, and metadata
        """
        if not self.ai_engine:
            # AI engine not wired — skip extraction. This is normal during
            # tests or minimal deployments that don't need automatic task extraction.
            return

        event_type = event.get("type", "")
        payload = event.get("payload", {})

        # --- Filter: Only process actionable event types ---
        # System events, predictions, and notifications are not actionable.
        # Only process events that contain user-generated text content.
        if event_type not in ["email.received", "message.received", "calendar.event.created"]:
            return

        # --- Extract text content from the event payload ---
        # Different event types store text in different fields. We extract
        # the most relevant text for LLM analysis.
        text = None
        if event_type == "email.received":
            # For emails, prioritize body > snippet > subject
            text = payload.get("body") or payload.get("snippet") or payload.get("subject", "")
        elif event_type == "message.received":
            # For messages, use the message body
            text = payload.get("body", "")
        elif event_type == "calendar.event.created":
            # For calendar events, check the description field for action items
            text = payload.get("description", "")

        # --- Filter: Skip empty or trivial messages ---
        # Don't waste LLM cycles on short messages like "ok", "thanks", etc.
        # Require at least 20 characters to reduce false positives.
        if not text or len(text.strip()) < 20:
            return

        # --- Call AI engine to extract action items ---
        # The AI engine returns a list of dicts: [{title, due_hint, priority}, ...]
        # Empty list means no action items were found (which is normal).
        try:
            action_items = await self.ai_engine.extract_action_items(text, event_type)
        except Exception as e:
            # Graceful degradation: if the AI engine fails (model down, parsing
            # error, etc.), log the error but don't crash the pipeline.
            # Task extraction is nice-to-have, not mission-critical.
            print(f"[TaskManager] AI extraction failed for event {event.get('id')}: {e}")
            return

        # --- Ingest extracted tasks into the database ---
        # Each task is linked back to the source event for full provenance.
        # The ingest_ai_extracted_tasks method handles the database writes.
        if action_items:
            await self.ingest_ai_extracted_tasks(action_items, event.get("id"))

    async def create_task(
        self,
        title: str,
        description: Optional[str] = None,
        source: str = "user",
        source_event_id: Optional[str] = None,
        source_context: Optional[str] = None,
        domain: Optional[str] = None,
        priority: str = "normal",
        tags: Optional[list[str]] = None,
        due_date: Optional[str] = None,
        reminder_at: Optional[str] = None,
        estimated_minutes: Optional[int] = None,
        related_contacts: Optional[list[str]] = None,
        related_events: Optional[list[str]] = None,
    ) -> str:
        """
        Create a new task. Returns the task ID.

        Tasks can originate from multiple sources:
            "user"         - manually created by the user
            "ai_extracted" - automatically extracted from emails/messages by the AI engine
            "rule"         - generated by a rules engine action
            "prediction"   - suggested by the prediction engine

        The source and source_event_id fields maintain full provenance so
        the user can always trace a task back to its origin.
        """
        task_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        # Persist the task with all metadata. List fields (tags,
        # related_contacts, related_events) are JSON-serialized for storage.
        with self.db.get_connection("state") as conn:
            conn.execute(
                """INSERT INTO tasks
                   (id, title, description, source, source_event_id, source_context,
                    domain, priority, tags, due_date, reminder_at, estimated_minutes,
                    related_contacts, related_events, status, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)""",
                (
                    task_id, title, description, source, source_event_id, source_context,
                    domain, priority,
                    json.dumps(tags or []),
                    due_date, reminder_at, estimated_minutes,
                    json.dumps(related_contacts or []),
                    json.dumps(related_events or []),
                    now, now,
                ),
            )

        await self._publish_telemetry("task.created", {
            "task_id": task_id,
            "title": title,
            "source": source,
            "source_event_id": source_event_id,
            "domain": domain,
            "priority": priority,
            "has_due_date": due_date is not None,
            "tags": tags or [],
            "created_at": now,
        })

        return task_id

    async def complete_task(self, task_id: str):
        """Mark a task as completed."""
        now = datetime.now(timezone.utc).isoformat()

        # Fetch task details before completing for telemetry
        task_details = {}
        with self.db.get_connection("state") as conn:
            row = conn.execute("SELECT title, source, domain, priority, created_at FROM tasks WHERE id = ?", (task_id,)).fetchone()
            if row:
                task_details = dict(row)
            conn.execute(
                "UPDATE tasks SET status = 'completed', completed_at = ?, updated_at = ? WHERE id = ?",
                (now, now, task_id),
            )

        await self._publish_telemetry("task.completed", {
            "task_id": task_id,
            "completed_at": now,
            **task_details,
        })

    async def update_task(self, task_id: str, **fields):
        """
        Update specific fields on a task.

        Only whitelisted fields can be updated to prevent accidental
        modification of audit fields (id, source, created_at, etc.).
        List fields are auto-serialized to JSON before storage.
        """
        allowed = {
            "title", "description", "domain", "priority", "tags",
            "due_date", "reminder_at", "estimated_minutes", "status",
        }
        # Filter to only allowed fields — silently drops unknown keys
        updates = {k: v for k, v in fields.items() if k in allowed}
        if not updates:
            return

        # Serialize list fields to JSON strings for SQLite storage
        for key in ("tags", "related_contacts", "related_events"):
            if key in updates and isinstance(updates[key], list):
                updates[key] = json.dumps(updates[key])

        # Build a dynamic UPDATE statement from the provided fields
        set_clause = ", ".join(f"{k} = ?" for k in updates)
        values = list(updates.values())
        values.append(datetime.now(timezone.utc).isoformat())  # updated_at
        values.append(task_id)  # WHERE clause

        with self.db.get_connection("state") as conn:
            conn.execute(
                f"UPDATE tasks SET {set_clause}, updated_at = ? WHERE id = ?",
                values,
            )

        await self._publish_telemetry("task.updated", {
            "task_id": task_id,
            "updated_fields": list(updates.keys()),
            "updated_at": datetime.now(timezone.utc).isoformat(),
        })

    def get_pending_tasks(
        self,
        domain: Optional[str] = None,
        priority: Optional[str] = None,
        limit: int = 50,
    ) -> list[dict]:
        """
        Get pending tasks, optionally filtered by domain and/or priority.

        Results are sorted by priority ordering (critical > high > normal > low)
        with a secondary sort by due date (earliest first, NULL dates last).
        This ensures the most urgent and time-sensitive tasks appear at the top.
        """
        query = "SELECT * FROM tasks WHERE status = 'pending'"
        params: list[Any] = []

        # Optional filters — dynamically appended to the WHERE clause
        if domain:
            query += " AND domain = ?"
            params.append(domain)
        if priority:
            query += " AND priority = ?"
            params.append(priority)

        # --- Priority ordering in queries ---
        # Tasks are sorted by: (1) priority rank, (2) due date.
        # NULLS LAST ensures tasks without a due date don't crowd out
        # tasks with upcoming deadlines.
        query += """
            ORDER BY
                CASE priority
                    WHEN 'critical' THEN 1 WHEN 'high' THEN 2
                    WHEN 'normal' THEN 3 ELSE 4
                END,
                due_date ASC NULLS LAST
            LIMIT ?"""
        params.append(limit)

        with self.db.get_connection("state") as conn:
            rows = conn.execute(query, params).fetchall()
            return [self._row_to_dict(row) for row in rows]

    def get_overdue_tasks(self) -> list[dict]:
        """Get tasks past their due date."""
        now = datetime.now(timezone.utc).isoformat()
        with self.db.get_connection("state") as conn:
            rows = conn.execute(
                """SELECT * FROM tasks
                   WHERE status = 'pending' AND due_date IS NOT NULL AND due_date < ?
                   ORDER BY due_date ASC""",
                (now,),
            ).fetchall()
            return [self._row_to_dict(row) for row in rows]

    def get_tasks_due_soon(self, hours: int = 24) -> list[dict]:
        """Get tasks due within the next N hours."""
        now = datetime.now(timezone.utc)
        deadline = (now + timedelta(hours=hours)).isoformat()
        with self.db.get_connection("state") as conn:
            rows = conn.execute(
                """SELECT * FROM tasks
                   WHERE status = 'pending' AND due_date IS NOT NULL
                   AND due_date BETWEEN ? AND ?
                   ORDER BY due_date ASC""",
                (now.isoformat(), deadline),
            ).fetchall()
            return [self._row_to_dict(row) for row in rows]

    def get_task_context(self, task_id: str) -> dict:
        """
        Get the full context for a task -- the original event that spawned it,
        related contacts, and any connected files or events.

        Task context assembly gathers everything the user needs to work on a
        task in one place:
            1. The task itself (title, description, priority, tags, etc.)
            2. The source event (e.g., the email that created the task)
            3. Related contacts (people involved, with full contact details)

        This is the "sit down and work" view -- when the user opens a task,
        they see the full picture without having to hunt for context.
        """
        with self.db.get_connection("state") as conn:
            task_row = conn.execute("SELECT * FROM tasks WHERE id = ?", (task_id,)).fetchone()

        if not task_row:
            return {}

        task = self._row_to_dict(task_row)
        context = {"task": task}

        # --- Source event retrieval ---
        # If the task was created from an event (e.g., an email or message),
        # fetch the full event record so the user can see the original context.
        if task.get("source_event_id"):
            with self.db.get_connection("events") as conn:
                event_row = conn.execute(
                    "SELECT * FROM events WHERE id = ?", (task["source_event_id"],)
                ).fetchone()
                if event_row:
                    context["source_event"] = dict(event_row)

        # --- Related contacts retrieval ---
        # Fetch full contact records for anyone associated with the task.
        # Uses a dynamic IN clause with parameterized placeholders.
        contact_ids = task.get("related_contacts", [])
        if contact_ids:
            with self.db.get_connection("entities") as conn:
                placeholders = ",".join("?" * len(contact_ids))
                contacts = conn.execute(
                    f"SELECT * FROM contacts WHERE id IN ({placeholders})",
                    contact_ids,
                ).fetchall()
                context["related_contacts"] = [dict(c) for c in contacts]

        return context

    async def ingest_ai_extracted_tasks(self, tasks: list[dict], source_event_id: str):
        """
        Store tasks extracted by the AI engine from messages/emails.

        AI-extracted task ingestion: the AI engine parses incoming messages
        and identifies actionable items (e.g., "Can you send me the report
        by Friday?"). Each extracted task is linked back to its source
        event via source_event_id so the user can see the original message.

        Each task dict should have: title, due_hint (optional), priority.
        """
        for task_data in tasks:
            await self.create_task(
                title=task_data.get("title", "Untitled task"),
                source="ai_extracted",           # Marks provenance as AI-extracted
                source_event_id=source_event_id,   # Links back to the originating message
                priority=task_data.get("priority", "normal"),
                due_date=task_data.get("due_hint"),  # AI's best guess at the deadline
            )

    def get_task_stats(self) -> dict:
        """
        Get summary statistics for the task dashboard.

        Returns counts for: pending tasks, tasks completed today, overdue
        tasks, and a breakdown of pending tasks by life domain.
        """
        with self.db.get_connection("state") as conn:
            pending = conn.execute(
                "SELECT COUNT(*) as cnt FROM tasks WHERE status = 'pending'"
            ).fetchone()["cnt"]

            completed_today = conn.execute(
                """SELECT COUNT(*) as cnt FROM tasks
                   WHERE status = 'completed'
                   AND completed_at > datetime('now', '-1 day')"""
            ).fetchone()["cnt"]

            overdue = conn.execute(
                """SELECT COUNT(*) as cnt FROM tasks
                   WHERE status = 'pending' AND due_date IS NOT NULL
                   AND due_date < datetime('now')"""
            ).fetchone()["cnt"]

            by_domain = conn.execute(
                """SELECT domain, COUNT(*) as cnt FROM tasks
                   WHERE status = 'pending' GROUP BY domain"""
            ).fetchall()

        return {
            "pending": pending,
            "completed_today": completed_today,
            "overdue": overdue,
            "by_domain": {row["domain"] or "unassigned": row["cnt"] for row in by_domain},
        }

    @staticmethod
    def _row_to_dict(row) -> dict:
        """
        Convert a database row to a dict, deserializing JSON list fields.

        List fields (tags, related_contacts, related_files, related_events,
        depends_on) are stored as JSON strings in SQLite. This helper
        transparently deserializes them back to Python lists so callers
        always work with native types.
        """
        d = dict(row)
        for field in ("tags", "related_contacts", "related_files", "related_events", "depends_on"):
            if field in d and isinstance(d[field], str):
                try:
                    d[field] = json.loads(d[field])
                except (json.JSONDecodeError, TypeError):
                    d[field] = []  # Fallback to empty list on malformed data
        return d
