"""Profile the five v1 Life OS SQLite databases (read-only).

Emits MIGRATION_PROFILE.md at the repo root. Opens every DB with
``mode=ro`` so nothing is written. Used as prework for the v2 rewrite
migration plan.

If ``./data/`` has no v1 DBs, a stub MIGRATION_PROFILE.md is written
instructing the operator to run this script on the Mac Mini where the
production DBs live.
"""

from __future__ import annotations

import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path

V1_DBS: tuple[str, ...] = (
    "events.db",
    "entities.db",
    "state.db",
    "user_model.db",
    "preferences.db",
)

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
OUTPUT = REPO_ROOT / "MIGRATION_PROFILE.md"


@dataclass
class TableInfo:
    name: str
    row_count: int
    byte_size: int
    fks: list[tuple[str, str, str]] = field(default_factory=list)


@dataclass
class DbInfo:
    db_name: str
    path: Path
    exists: bool
    file_size: int = 0
    wal_size: int = 0
    tables: list[TableInfo] = field(default_factory=list)
    error: str | None = None


def _open_ro(path: Path) -> sqlite3.Connection:
    uri = f"file:{path}?mode=ro"
    return sqlite3.connect(uri, uri=True)


def _byte_size(conn: sqlite3.Connection, table: str) -> int:
    cur = conn.execute(
        "SELECT COALESCE(SUM(pgsize), 0) FROM dbstat WHERE name = ?",
        (table,),
    )
    row = cur.fetchone()
    return int(row[0]) if row and row[0] is not None else 0


def _tables(conn: sqlite3.Connection) -> list[str]:
    cur = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    return [r[0] for r in cur.fetchall()]


def _fks(conn: sqlite3.Connection, table: str) -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []
    try:
        cur = conn.execute(f"PRAGMA foreign_key_list('{table}')")
        for row in cur.fetchall():
            # row layout: id, seq, table, from, to, on_update, on_delete, match
            out.append((row[3], row[2], row[4]))
    except sqlite3.DatabaseError:
        pass
    return out


def _row_count(conn: sqlite3.Connection, table: str) -> int:
    try:
        cur = conn.execute(f'SELECT COUNT(*) FROM "{table}"')
        return int(cur.fetchone()[0])
    except sqlite3.DatabaseError:
        return -1


def profile_db(db_name: str, data_dir: Path) -> DbInfo:
    path = data_dir / db_name
    info = DbInfo(db_name=db_name, path=path, exists=path.exists())
    if not info.exists:
        return info
    info.file_size = path.stat().st_size
    wal = path.with_name(f"{db_name}-wal")
    if wal.exists():
        info.wal_size = wal.stat().st_size
    try:
        with _open_ro(path) as conn:
            has_dbstat = True
            try:
                conn.execute("SELECT 1 FROM dbstat LIMIT 1")
            except sqlite3.DatabaseError:
                has_dbstat = False
            for t in _tables(conn):
                info.tables.append(
                    TableInfo(
                        name=t,
                        row_count=_row_count(conn, t),
                        byte_size=_byte_size(conn, t) if has_dbstat else 0,
                        fks=_fks(conn, t),
                    )
                )
    except sqlite3.DatabaseError as e:
        info.error = str(e)
    return info


def events_by_source(data_dir: Path) -> list[tuple[str, int]] | None:
    path = data_dir / "events.db"
    if not path.exists():
        return None
    try:
        with _open_ro(path) as conn:
            cur = conn.execute("SELECT source, COUNT(*) FROM events GROUP BY source ORDER BY COUNT(*) DESC")
            return [(r[0], int(r[1])) for r in cur.fetchall()]
    except sqlite3.DatabaseError:
        return None


def _fmt_bytes(n: int) -> str:
    step = 1024.0
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if n < step:
            return f"{n:.1f} {unit}" if unit != "B" else f"{n} B"
        n = int(n / step)
    return f"{n} PiB"


def _render_stub() -> str:
    return (
        "# MIGRATION_PROFILE\n\n"
        "> **STUB** — no `./data/` v1 DBs found on this machine.\n"
        ">\n"
        "> Run `python scripts/profile_v1_dbs.py` on the Mac Mini "
        "(where the production DBs live) to regenerate this file with "
        "real numbers.\n\n"
        f"Expected DBs at `./data/`: {', '.join(V1_DBS)}.\n"
    )


def _render_report(dbs: list[DbInfo]) -> str:
    lines: list[str] = ["# MIGRATION_PROFILE", ""]
    lines.append("Generated by `scripts/profile_v1_dbs.py`.")
    lines.append("")

    lines.append("## Summary")
    total_file = sum(d.file_size for d in dbs)
    total_wal = sum(d.wal_size for d in dbs)
    total_rows = sum(sum(t.row_count for t in d.tables if t.row_count >= 0) for d in dbs)
    lines.append(f"- Total data size (files): {_fmt_bytes(total_file)}")
    lines.append(f"- Total WAL overhead: {_fmt_bytes(total_wal)}")
    lines.append(f"- Total rows across all tables: {total_rows:,}")
    present = [d.db_name for d in dbs if d.exists]
    missing = [d.db_name for d in dbs if not d.exists]
    lines.append(f"- DBs present ({len(present)}): {', '.join(present) or '—'}")
    if missing:
        lines.append(f"- DBs missing: {', '.join(missing)}")
    lines.append("")

    all_tables: list[tuple[str, str, int, int]] = []
    for d in dbs:
        for t in d.tables:
            all_tables.append((d.db_name, t.name, t.row_count, t.byte_size))
    top5 = sorted(all_tables, key=lambda r: r[3], reverse=True)[:5]
    if top5:
        lines.append("## Top 5 largest tables (by bytes)")
        lines.append("")
        lines.append("| DB | Table | Rows | Size |")
        lines.append("|---|---|---:|---:|")
        for db, tbl, rows, sz in top5:
            lines.append(f"| `{db}` | `{tbl}` | {rows:,} | {_fmt_bytes(sz)} |")
        lines.append("")

    for d in dbs:
        lines.append(f"## `{d.db_name}`")
        if not d.exists:
            lines.append("_Not present._")
            lines.append("")
            continue
        lines.append(f"- Path: `{d.path}`")
        lines.append(f"- File size: {_fmt_bytes(d.file_size)}")
        lines.append(f"- WAL size: {_fmt_bytes(d.wal_size)}")
        if d.error:
            lines.append(f"- Error: `{d.error}`")
        if d.tables:
            lines.append("")
            lines.append("| Table | Rows | Size |")
            lines.append("|---|---:|---:|")
            for t in sorted(d.tables, key=lambda x: x.byte_size, reverse=True):
                lines.append(f"| `{t.name}` | {t.row_count:,} | {_fmt_bytes(t.byte_size)} |")
            fk_edges: list[str] = []
            for t in d.tables:
                for col, ref_tbl, ref_col in t.fks:
                    fk_edges.append(f"`{t.name}.{col}` → `{ref_tbl}.{ref_col}`")
            if fk_edges:
                lines.append("")
                lines.append("**FK graph:**")
                lines.append("")
                for edge in fk_edges:
                    lines.append(f"- {edge}")
        lines.append("")

    by_source = events_by_source(DATA_DIR)
    if by_source is not None:
        lines.append("## `events` by `source`")
        lines.append("")
        lines.append("| Source | Count |")
        lines.append("|---|---:|")
        for src, n in by_source:
            lines.append(f"| `{src}` | {n:,} |")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not DATA_DIR.exists():
        OUTPUT.write_text(_render_stub())
        print(f"No {DATA_DIR} directory; wrote stub {OUTPUT}")
        return 0

    dbs = [profile_db(name, DATA_DIR) for name in V1_DBS]
    if not any(d.exists for d in dbs):
        OUTPUT.write_text(_render_stub())
        print(f"No v1 DBs found under {DATA_DIR}; wrote stub {OUTPUT}")
        return 0

    report = _render_report(dbs)
    OUTPUT.write_text(report)
    print(f"Wrote {OUTPUT} ({len(report):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
